WindFormCartoons/MvcCartoons/Controllers/AddCartoonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassCartoons;

namespace MvcCartoons.Controllers
{
    public class AddCartoonController : Controller
    {
        private DBCartoonsEntities db = new DBCartoonsEntities();
        //
        // GET: /AddCartoon/

        public ActionResult Index()
        {
            return View(db.CARTOONS.ToList());
        }

        //
        // GET: /AddCartoon/Details/5

        public ActionResult Details(int id = 0)
        {
            CARTOONS car = db.CARTOONS.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        //
        // GET: /AddCartoon/Create

        public ActionResult Create()
        {
            var car = new CARTOONS();
            ViewBag.Statuses = db.DIC_CARTOON_STATUSES.ToList();
            return View(car);
        }

        [HttpPost]
        public ActionResult Create(CARTOONS car)
        {
            if (ModelState.IsValid)
            {
                db.CARTOONS.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(car);
        }

        //
        // GET: /AddCartoon/Edit/5

        public ActionResult Edit(int id)
        {
            CARTOONS car = db.CARTOONS.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarName = car.CR_NAME;
            return View(car);
        }

        [HttpPost]
        public ActionResult Edit(CARTOONS car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        //
        // GET: /AddCartoon/Delete/5

        public ActionResult Delete(int id)
        {
            CARTOONS car = db.CARTOONS.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarName = car.CR_NAME;
            return View(car);
        }

        //
        // POST: /Film/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            CARTOONS car = db.CARTOONS.Find(id);
            db.CARTOONS.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WindFormCartoons/MvcCartoons/Controllers/CartoonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassCartoons;

namespace MvcCartoons.Controllers
{
    public class CartoonsController : Controller
    {
        private DBCartoonsEntities db = new DBCartoonsEntities();
        //
        // GET: /Cartoons/

        public ActionResult Index()
        {
            return View(db.DIC_GENRE.ToList());
        }

        public ActionResult CartoonsByGenre(int id)
        {
            ViewBag.CategoryName = db.DIC_GENRE.Where(x => x.GR_ID == id).First().GR_NAME;
            return View(db.CARTOONS.Where(x => x.GENRE_CARTOONS.Any(y => y.GC_GR == id)).ToList());

        }

        /*public ActionResult CartoonDetails(int diractorID, int companyID,  int id)
        {

            return PartialView(db.CARTOONS.Include("DIC_DIRACTORS", "DIC_COMPANY", "CARTOONS").First(x => x.CR_ID == id));
        }*/

        public ActionResult DiractorsByCartoons (int id)
        {
            ViewBag.CartoonName = db.CARTOONS.Where(x => x.CR_ID == id).First().CR_NAME;
            return View(db.DIC_DIRACTORS.Where(x => x.DIRACTORS_CARTOONS.Any(y => y.DK_CR == id)).ToList());
        }

        public ActionResult Cartoons()
        {
            return View(db.CARTOONS.ToList());
        }

        public ActionResult CartoonsByCompany(int id)
        {
            ViewBag.CartoonName = db.CARTOONS.Where(x => x.CR_ID == id).First().CR_NAME;
            return View(db.DIC_COMPANY.Where(x => x.COMPANY_CARTOONS.Any(y => y.CC_CR == id)).ToList());
        }

        public ActionResult Company()
        {
            return View(db.DIC_COUNRTY);
        }

        public ActionResult CartoonsByCountry(int id)
        {
            ViewBag.CountryName = db.DIC_COUNRTY.Where(x => x.CT_ID == id).First().CT_NAME;
            return   View(db.CARTOONS.Where(x => x.COMPANY_CARTOONS.Any(y => y.DIC_COMPANY.DIC_COUNRTY.CT_ID == id)).ToList());
        }
    }
}

WindFormCartoons/MvcCartoons/Controllers/DiractorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassCartoons;

namespace MvcCartoons.Controllers
{
    public class DiractorController : Controller
    {
        private DBCartoonsEntities db = new DBCartoonsEntities();
        //
        // GET: /Diractor/

        public ActionResult Index()
        {
            return View(db.DIC_DIRACTORS.ToList());
        }

        //
        // GET: /Diractor/Details/5

        public ActionResult Details(int id = 0)
        {
            DIC_DIRACTORS diractors = db.DIC_DIRACTORS.Find(id);
            if (diractors == null)
            {
                return HttpNotFound();
            }
            return View(diractors);
        }

        //
        // GET: /Diractor/Create

        public ActionResult Create()
        {
            var dir = new DIC_DIRACTORS();
            return View(dir);
        }

        [HttpPost]
        public ActionResult Create(DIC_DIRACTORS dir)
        {
            if (ModelState.IsValid)
            {
                db.DIC_DIRACTORS.Add(dir);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dir);
        }

        //
        // GET: /Diractor/Edit/5

        public ActionResult Edit(int id)
        {
            DIC_DIRACTORS dir = db.DIC_DIRACTORS.Find(id);
            if (dir == null)
            {
                return HttpNotFound();
            }
            ViewBag.DirName = dir.DR_NAME;
            return View(dir);
        }

        [HttpPost]
        public ActionResult Edit(DIC_DIRACTORS dir)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dir).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dir);
        }

        //
        // GET: /Diractor/Delete/5


        public ActionResult Delete(int id)
        {
            DIC_DIRACTORS dir = db.DIC_DIRACTORS.Find(id);
            if (dir == null)
            {
                return HttpNotFound();
            }
            ViewBag.DirName = dir.DR_NAME;
            return View(dir);
        }

        //
        // POST: /Film/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            DIC_DIRACTORS dir = db.DIC_DIRACTORS.Find(id);
            db.DIC_DIRACTORS.Remove(dir);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WindFormCartoons/MvcCartoons/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title — приложение ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("КІНОЗАЛ", "Index", "Cartoons")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Жанри", "Index", "Cartoons")</li>
                            <li>@Html.ActionLink("Режисери", "Index", "Diractor")</li>
                            <li>@Html.ActionLink("Мультфільми", "Index", "AddCartoon")</li>
                            <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year — Кінозал</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>